### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by JulienVerkest** [vazra/react-ts-rxdb-bootstrap-table#92]
I clone the repository, launch a  `npm install` command and a `npm start`  and I have this error message on http://localhost:3000/react-ts-rxdb-bootstrap-table

```
./src/components/Dashboard.tsx
  Line 0:  Parsing error: Cannot read property 'map' of undefined
```

**Comment by vazra** [comment]
Hey @JulienVerkest , 
can you try `git reset --hard f6da37ec7f02a45b55a527819789a4a96180bb34` in your local repo, and reinstall  with yarn/npm and try running again?

**Comment by JulienVerkest** [comment]
@vazra It works fine! Thanks you.
